#!/usr/bin/env bash
#
# install.sh — Bootstrap the project-name development environment.
#
# Installs all Python and JavaScript dependencies, copies missing .env.*
# files from their examples, marks every project script executable, and
# (on first run) renames all project-name placeholders to your project name.
#
# Usage: bash install.sh
#
# Requirements: uv >= 0.11, pnpm >= 10.33
#
# Exit codes:  0 = success   1 = requirement missing   2 = install failed
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# ── Helpers ───────────────────────────────────────────────────────────────────
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
log()   { printf '  %s\n' "$*"; }
ok()    { printf '  \033[32m✓\033[0m  %s\n' "$*"; }
warn()  { printf '  \033[33m⚠\033[0m  %s\n' "$*"; }
err()   { printf '\033[31merror:\033[0m %s\n' "$*" >&2; }
die()   { err "$*"; exit 1; }

# ── Preflight checks ──────────────────────────────────────────────────────────
bold "▸ install.sh — project-name"
log ""

command -v uv   >/dev/null 2>&1 || die "uv is not installed. See https://docs.astral.sh/uv/getting-started/installation/"
command -v pnpm >/dev/null 2>&1 || die "pnpm is not installed. See https://pnpm.io/installation"

UV_VERSION=$(uv --version 2>&1 | awk '{print $2}')
PNPM_VERSION=$(pnpm --version 2>&1)
log "uv   $UV_VERSION"
log "pnpm $PNPM_VERSION"
log ""

cd "$PROJECT_ROOT"

# ── Project name ──────────────────────────────────────────────────────────────
NAMED_MARKER="$PROJECT_ROOT/.project-named"

if [[ -f "$NAMED_MARKER" ]]; then
  log "  Project name already set (delete .project-named to re-run renaming)."
  log ""
elif [[ ! -t 0 ]]; then
  warn "Non-interactive mode — skipping project name prompt."
  log "  Re-run install.sh in a terminal to rename placeholders."
  log ""
else
  bold "── Project name ─────────────────────────────────────────────────────────"
  log ""
  log "  This scaffold uses 'project-name' as a placeholder throughout."
  log "  Enter your project name and all occurrences will be renamed now."
  log ""
  log "  Accepted formats: 'My Project', 'my-project', 'my_project', 'MyProject'"
  log ""

  while true; do
    printf '  Project name: '
    read -r raw_name

    raw_name=$(echo "$raw_name" | sed 's/^ *//;s/ *$//')

    if [[ -z "$raw_name" ]]; then
      warn "Name cannot be empty — try again."
      continue
    fi

    # Normalise any input format into space-separated lowercase words:
    # 1. Insert space before a lowercase→uppercase transition  (camelCase)
    # 2. Insert space before an uppercase run followed by uppercase+lower (acronym)
    # 3. Lowercase everything
    # 4. Replace hyphens and underscores with spaces
    # 5. Collapse multiple spaces
    normalized=$(echo "$raw_name" \
      | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g' \
      | sed 's/\([A-Z][A-Z]*\)\([A-Z][a-z]\)/\1 \2/g' \
      | tr '[:upper:]' '[:lower:]' \
      | tr '-_' '  ' \
      | tr -s ' ' \
      | sed 's/^ *//;s/ *$//')

    NEW_KEBAB=$(echo "$normalized" | tr ' ' '-')
    NEW_SNAKE=$(echo "$normalized" | tr ' ' '_')
    NEW_LOWER=$(echo "$normalized" | tr -d ' ')
    NEW_PASCAL=$(echo "$normalized" \
      | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1' \
      | tr -d ' ')

    log ""
    log "  Preview:"
    log "    kebab  : $NEW_KEBAB   (replaces 'project-name')"
    log "    snake  : $NEW_SNAKE  (replaces 'project_name')"
    log "    pascal : $NEW_PASCAL  (replaces 'ProjectName')"
    log "    lower  : $NEW_LOWER  (replaces 'projectname')"
    log ""
    printf '  Confirm? [Y/n]: '
    read -r confirm

    case "$confirm" in
      [nN]*) log ""; warn "Re-entering name..."; log ""; continue ;;
      *) break ;;
    esac
  done

  log ""
  log "  Renaming placeholders in all tracked files..."

  # Escape a string for use as a sed replacement (escapes / \ &)
  sed_escape() { printf '%s' "$1" | sed 's/[\/\\&]/\\&/g'; }

  E_KEBAB=$(sed_escape "$NEW_KEBAB")
  E_SNAKE=$(sed_escape "$NEW_SNAKE")
  E_LOWER=$(sed_escape "$NEW_LOWER")
  E_PASCAL=$(sed_escape "$NEW_PASCAL")

  RENAMED=0

  while IFS= read -r file; do
    # Skip auto-generated lock files — regenerated by uv/pnpm on next run
    [[ "$file" == "uv.lock" ]]        && continue
    [[ "$file" == "pnpm-lock.yaml" ]] && continue
    [[ -f "$file" ]]                  || continue
    # Skip binary files (grep -I exits non-zero when no text matches)
    grep -qI '' "$file" 2>/dev/null   || continue

    # All four replacements in a single sed pass (most-specific patterns first)
    sed -i \
      -e "s/project-name/$E_KEBAB/g" \
      -e "s/project_name/$E_SNAKE/g" \
      -e "s/ProjectName/$E_PASCAL/g" \
      -e "s/projectname/$E_LOWER/g"  \
      "$file" 2>/dev/null && RENAMED=$((RENAMED + 1))

  done < <(git -C "$PROJECT_ROOT" ls-files)

  touch "$NAMED_MARKER"
  log ""
  ok "$RENAMED files processed — placeholders replaced with '$NEW_KEBAB'"
  log ""
fi

# ── Python dependencies ───────────────────────────────────────────────────────
bold "── Python (uv sync) ──────────────────────────────────────────────────────"
log ""
uv sync --all-groups || { err "uv sync failed"; exit 2; }
log ""
ok "Python dependencies installed (.venv)"
log ""

# ── code-review-graph MCP server ──────────────────────────────────────────────
bold "── code-review-graph (MCP server) ───────────────────────────────────────"
log ""

CRG_BIN="$PROJECT_ROOT/.venv/bin/code-review-graph"

if [[ ! -f "$CRG_BIN" ]]; then
  log "  Installing code-review-graph into .venv..."
  if uv pip install code-review-graph 2>&1 | tail -1; then
    log ""
  else
    warn "Could not install code-review-graph automatically."
    warn "Install manually after setup:  uv pip install code-review-graph"
    log ""
  fi
fi

if [[ -f "$CRG_BIN" ]]; then
  ok "code-review-graph binary ready at .venv/bin/code-review-graph"
  log ""
  log "  .mcp.json already configures it as the 'code-review-graph' MCP server."
  log "  Claude Code loads it automatically on next launch — no extra setup needed."
else
  warn "code-review-graph binary not found — MCP server will be unavailable until"
  warn "you run:  uv pip install code-review-graph"
fi
log ""

# ── JavaScript dependencies ───────────────────────────────────────────────────
bold "── JavaScript (pnpm install) ─────────────────────────────────────────────"
log ""
pnpm install || { err "pnpm install failed"; exit 2; }
log ""
ok "JavaScript dependencies installed (node_modules)"
log ""

# ── Environment files ─────────────────────────────────────────────────────────
bold "── Environment files ────────────────────────────────────────────────────"
log ""

ENV_DIR="$PROJECT_ROOT/code/src/docker"
COPIED=()
SKIPPED=()

for example in "$ENV_DIR"/.env.*.example; do
  target="${example%.example}"
  if [[ ! -f "$target" ]]; then
    cp "$example" "$target"
    COPIED+=("$(basename "$target")")
  else
    SKIPPED+=("$(basename "$target")")
  fi
done

for f in "${COPIED[@]+"${COPIED[@]}"}";   do ok "created  code/src/docker/$f"; done
for f in "${SKIPPED[@]+"${SKIPPED[@]}"}"; do log "skipped  code/src/docker/$f (already exists)"; done
log ""

if [[ ${#COPIED[@]} -gt 0 ]]; then
  printf '  \033[33m⚠  All secrets in the following files must be populated before\033[0m\n'
  printf '  \033[33m   starting any environment:\033[0m\n'
  log ""
  for f in "${COPIED[@]}"; do
    log "     code/src/docker/$f"
  done
  log ""
fi

# ── Script permissions ────────────────────────────────────────────────────────
bold "── Script permissions (chmod +x) ────────────────────────────────────────"
log ""

chmod +x "$PROJECT_ROOT/install.sh"
find "$PROJECT_ROOT/code/src/scripts" -name "*.sh" -exec chmod +x {} \;

SCRIPT_COUNT=$(find "$PROJECT_ROOT/code/src/scripts" -name "*.sh" | wc -l | tr -d ' ')
ok "$SCRIPT_COUNT scripts marked executable"
log ""

# ── Done ──────────────────────────────────────────────────────────────────────
bold "✓ Ready. Next: populate code/src/docker/.env.* secrets, then run ./code/src/scripts/development/server.sh up"
log ""
